repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
repos:        
- repo: https://github.com/dfm/black_nbconvert
  rev: stable
  hooks:
  - id: black_nbconvert
